// High-converting services configuration
export const validServices = {
  "custom-website-development": {
    name: "Custom Website Development",
    description:
      "Professional custom website development tailored to your business needs",
    startingPrice: "$2,999",
    keywords: [
      "custom website",
      "web development",
      "business website",
      "professional website",
    ],
    benefits: [
      "100% custom design tailored to your brand",
      "Mobile-responsive across all devices",
      "SEO-optimized for search engines",
      "Fast loading speed and performance",
      "Secure and reliable hosting included",
    ],
    process: [
      "Discovery & Strategy Session",
      "Custom Design & Wireframing",
      "Development & Integration",
      "Testing & Launch",
    ],
    features: [
      "Custom Design & Branding",
      "Mobile-Responsive Layout",
      "SEO Optimization",
      "Content Management System",
      "Security & SSL Certificate",
      "Analytics & Tracking Setup",
    ],
    deliverables: [
      "Fully functional custom website",
      "Mobile-responsive design",
      "SEO-optimized content structure",
      "Content management system",
      "1 year of hosting & support",
    ],
  },
  "website-redesign-optimization": {
    name: "Website Redesign & Optimization",
    description:
      "Transform your outdated website into a modern, high-converting digital presence",
    startingPrice: "$1,999",
    keywords: [
      "website redesign",
      "website optimization",
      "website makeover",
      "website refresh",
    ],
    benefits: [
      "Modern, professional design that builds trust",
      "Improved user experience and navigation",
      "Better search engine rankings",
      "Higher conversion rates and lead generation",
      "Mobile-first responsive design",
    ],
    process: [
      "Website Audit & Analysis",
      "Redesign Strategy & Planning",
      "Design & Development",
      "Testing & Optimization",
    ],
    features: [
      "Complete Website Redesign",
      "Performance Optimization",
      "SEO Improvements",
      "Mobile Optimization",
      "User Experience Enhancement",
      "Conversion Rate Optimization",
    ],
    deliverables: [
      "Completely redesigned website",
      "Performance optimization report",
      "SEO improvement implementation",
      "Mobile-responsive upgrade",
      "3 months of optimization support",
    ],
  },
  "local-seo-optimization": {
    name: "Local SEO Optimization",
    description:
      "Dominate local search results and attract more customers in your area",
    startingPrice: "$899",
    keywords: [
      "local SEO",
      "local search",
      "Google My Business",
      "local rankings",
    ],
    benefits: [
      "Rank higher in local search results",
      "Attract more local customers",
      "Increase website traffic and calls",
      "Build local business credibility",
      "Outrank your competition",
    ],
    process: [
      "Local SEO Audit & Research",
      "Google My Business Optimization",
      "Local Citation Building",
      "Review Management Setup",
    ],
    features: [
      "Google My Business Optimization",
      "Local Keyword Research",
      "Local Citation Building",
      "Review Management",
      "Local Content Creation",
      "Local Link Building",
    ],
    deliverables: [
      "Optimized Google My Business profile",
      "Local citation submissions",
      "Local keyword optimization",
      "Review management system",
      "Monthly SEO performance reports",
    ],
  },
  "google-business-management": {
    name: "Google Business Management",
    description:
      "Professional Google Business Profile setup and management to attract local customers",
    startingPrice: "$599",
    keywords: [
      "Google Business",
      "Google My Business",
      "local business",
      "business profile",
    ],
    benefits: [
      "Professional Google Business Profile",
      "Increased local visibility",
      "More customer calls and directions",
      "Enhanced business credibility",
      "Improved local search rankings",
    ],
    process: [
      "Business Profile Setup",
      "Optimization & Enhancement",
      "Photo & Content Upload",
      "Ongoing Management",
    ],
    features: [
      "Complete Profile Setup",
      "Professional Photos",
      "Business Information Optimization",
      "Customer Review Management",
      "Post Creation & Scheduling",
      "Performance Tracking",
    ],
    deliverables: [
      "Fully optimized Google Business Profile",
      "Professional business photos",
      "Review management system",
      "Monthly posting schedule",
      "Performance tracking dashboard",
    ],
  },
  "e-commerce-solutions": {
    name: "E-commerce Solutions",
    description:
      "Complete e-commerce website development to sell your products online",
    startingPrice: "$3,999",
    keywords: ["e-commerce", "online store", "sell online", "shopping cart"],
    benefits: [
      "Professional online store design",
      "Secure payment processing",
      "Inventory management system",
      "24/7 sales capability",
      "Mobile-optimized shopping experience",
    ],
    process: [
      "E-commerce Strategy & Planning",
      "Store Design & Development",
      "Payment & Shipping Setup",
      "Testing & Launch",
    ],
    features: [
      "Custom E-commerce Design",
      "Secure Payment Processing",
      "Inventory Management",
      "Shopping Cart & Checkout",
      "Product Management System",
      "Order Management",
    ],
    deliverables: [
      "Complete e-commerce website",
      "Payment gateway integration",
      "Inventory management system",
      "Order processing workflow",
      "E-commerce training & support",
    ],
  },
  "social-media-setup": {
    name: "Social Media Setup",
    description:
      "Professional social media presence setup and optimization for your business",
    startingPrice: "$799",
    keywords: [
      "social media",
      "Facebook",
      "Instagram",
      "social media marketing",
    ],
    benefits: [
      "Professional social media presence",
      "Consistent brand messaging",
      "Increased online visibility",
      "Better customer engagement",
      "Streamlined social media management",
    ],
    process: [
      "Social Media Strategy",
      "Profile Setup & Optimization",
      "Content Creation & Branding",
      "Launch & Training",
    ],
    features: [
      "Multi-Platform Setup",
      "Professional Profile Design",
      "Content Template Creation",
      "Brand Consistency",
      "Social Media Guidelines",
      "Analytics Setup",
    ],
    deliverables: [
      "Optimized social media profiles",
      "Professional branding across platforms",
      "Content templates and guidelines",
      "Social media management training",
      "Performance tracking setup",
    ],
  },
};

// Valid locations for SEO and tracking
export const validLocations = [
  // Southwest Florida (SWFL) - Primary target region
  "cape-coral",
  "fort-myers",
  "naples",
  "bonita-springs",
  "estero",
  "sanibel",
  "fort-myers-beach",
  "marco-island",
  "punta-gorda",
  "port-charlotte",
  "venice",
  "sarasota",
  "bradenton",
  "lehigh-acres",
  "golden-gate",
  "immokalee",
  "labelle",
  "palmetto",
  "englewood",
  "north-port",
  "osprey",
  "siesta-key",
  "longboat-key",
  "anna-maria-island",
  "holmes-beach",
  "bradenton-beach",
  "palmetto-bay",
  "southwest-florida",
  "swfl",
  "florida",
  // Expanded Florida coverage
  "tampa",
  "st-petersburg",
  "clearwater",
  "lakeland",
  "winter-haven",
  "ocala",
  "gainesville",
  "tallahassee",
  "jacksonville",
  "orlando",
  "kissimmee",
  "winter-park",
  "sanford",
  "melbourne",
  "cocoa-beach",
  "vero-beach",
  "stuart",
  "west-palm-beach",
  "boca-raton",
  "delray-beach",
  "boynton-beach",
  "lake-worth",
  "palm-beach",
  "jupiter",
  "fort-lauderdale",
  "hollywood",
  "pembroke-pines",
  "coral-springs",
  "sunrise",
  "plantation",
  "davie",
  "weston",
  "miami",
  "miami-beach",
  "coral-gables",
  "homestead",
  "key-largo",
  "marathon",
  "key-west",
];
